### PR TITLE
feat: Adapt Dialog to use Drawers on mobile

### LINKED ISSUE #13338: [CAL-2978] Adapt Dialog to use Drawers on modals
@shadcn UI has a great example of this. We should do something simular and ensure we match our design system.

Discussed with @Jaibles in DMs and we think this is a good approach as our modals can get a bit messy on mobile with some nasty scrolling. 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2978](https://linear.app/calcom/issue/CAL-2978/adapt-dialog-to-use-drawers-on-modals)</sub>

### PR DESCRIPTION
**Pull request by gramo37**
## What does this PR do?

Fixes the below issue.
[CAL-2978] Adapt Dialog to use Drawers on modals https://github.com/calcom/cal.com/issues/13338

fixes https://github.com/calcom/cal.com/issues/13338

Please refer the below video and let me know if the solution is as expected:

Screen recordings of Production build ->
https://www.loom.com/share/50f6857055ec4bb0848f7d5d287fc52c?sid=2015e908-3942-4a0c-b469-9f64358d0bbd

https://www.loom.com/share/51e98373a2424d90b09cdf528af8eea3?t=51&sid=295c5ed6-5d99-408f-9c60-e7c6b0ac54ed

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?
- Open any dialog.
- Adjust the screen width to observe the changes.

### CODE REVIEW

**Comment by anikdhabal** [comment]
Hey @gramo37, thanks for fixing the conflict. Have you addressed the comments I left in the closed one?

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Hey @gramo37, thanks for fixing the conflict. Have you addressed the comments I left in the closed one?

**Comment by gramo37** [comment]
> Hey @gramo37, thanks for fixing the conflict. Have you addressed the comments I left in the closed one?

Yes, I am working on them.

**Comment by gramo37** [comment]
Hi @anikdhabal, I have fixed the mentioned problems except for one. Regarding the third issue, where the dialog was shown before the drawer, did you test that after building the application? I am unable to recreate the bug.

**Review by anikdhabal — COMMENTED** [review]
hey @gramo37 great work so far. Can you pls fix the unit test?

**Review by anikdhabal — COMMENTED** [review]
Screenshot 2024-06-29 171241

Screenshot 2024-06-29 180140

Screenshot 2024-07-17 201013

**Review by anikdhabal — COMMENTED** [review]
https://github.com/calcom/cal.com/assets/81948346/d439d786-606e-4c44-bb8f-36c067c1a352

**Review by anikdhabal — COMMENTED** [review]
https://github.com/calcom/cal.com/assets/81948346/7552e63e-f62d-4eff-9b40-6d8b96ea4d2a

This error is still there, and I've encountered it not only in the vent-type dialog but also in two other dialogs. @Udit-takkar, could you please test this once?

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Hey @gramo37, I suggest you go through all the requested changes made in the old PR. There are still some issues. Please address them.

**Comment by gramo37** [comment]
Hi @anikdhabal, as you mentioned, I have reworked this from the start and created a new pull request: https://github.com/calcom/cal.com/pull/15941. I have also tested it. Could you please test it and let me know if any bugs persist?

**Comment by anikdhabal** [comment]
> Hi @anikdhabal, as you mentioned, I have reworked this from the start and created a new pull request: #15941. I have also tested it. Could you please test it and let me know if any bugs persist?

Hey @gramo37, can you continue and finish the task in this PR instead of creating a new one? I don't think there is a need for a continuation part. Please try to add this feature in this PR. Addressed the requested changes here.

**Comment by gramo37** [comment]
Yeah sure @anikdhabal.

**Comment by gramo37** [comment]
Hi @anikdhabal,

I have pushed the changes in this pull request. I fixed the Dialog.tsx component to handle all the errors within the file itself, so there is no need to make changes to individual files.

**Comment by anikdhabal** [comment]
Thanks @gramo37 I will check that

**Comment by gramo37** [comment]
Sure, here are some of the test cases I used to test it:

1) /event-types/23?tabName=advanced

https://github.com/user-attachments/assets/7694b2f1-aadf-4921-8127-cb5d528d4188

2) /availability and /event-types

https://github.com/user-attachments/assets/28b62df1-b10e-4f9f-93e7-d81f858b0186

3) /bookings/upcoming

https://github.com/user-attachments/assets/ce0bf713-d972-4344-a821-4cfc742639a6

4) /apps/installed/conferencing

https://github.com/user-attachments/assets/0cbbdbfc-07f1-4c83-858c-90cd4d34eeff

5) /settings/security/two-factor-auth

https://github.com/user-attachments/assets/ad5314d8-b7e0-4cf4-970a-eb502bc06622

6) /settings/teams/280/onboard-members?id=280

https://github.com/user-attachments/assets/0647050a-9d81-410b-add5-6dd45613307b

7) /settings/teams/280/members

https://github.com/user-attachments/assets/d55b1534-0de4-4c44-80da-03c6c16b9695

Please let me know if I missed something.

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Unit Tests are failing

**Comment by Amit91848** [comment]
Clicking outside the modal removes query params from url, but does not do it for drawers. This prevents the modal from opening.

https://github.com/user-attachments/assets/268db9b9-9032-4bea-aa82-f7df61c2c5b0

**Comment by Amit91848** [comment]
Great work so far @gramo37 . Found some more minor issues

- Inside Custom Event Name modal, **Preview** is zoomed in. Not sure if this is a big deal tho
   Screenshot 2024-07-31 150148
- Cannot reopen out of office modal after closing it with swipe down
  
   https://github.com/user-attachments/assets/c4c9ffcc-4921-46d5-8995-1194ffbd0ce1
   
- Opens keyboard which covers the select when changing invite link settings. Happens with normal dialog too. 
  Keyboard does not open when you are changing user roles, you could change the settings for invite link as not opening the keyboard would be better
  
  https://github.com/user-attachments/assets/1f718fae-0a41-4eb2-b915-0d6f6d6e5b97

**Comment by gramo37** [comment]
For the third issue, specifically with reopening the out-of-office modal after closing it by swiping down, the problem arises because there is no onOpenChange prop given to the Dialog. If I add it, the issue is resolved. However, there are seven more similar cases. This issue does not occur in Desktop, as the only way to cancel them is by pressing the cancel button.

An alternative solution is to disable the swipe-down functionality if onOpenChange is not present, forcing users to press the cancel button instead.

https://github.com/user-attachments/assets/bd98e412-a21f-44ab-b36b-9d1a355e3ba6

@anikdhabal and @Amit91848, please let me know which solution we should proceed with.

**Comment by Amit91848** [comment]
It's better to have the consistent behaviour everywhere, since we are making changes, might as well add onOpenChange prop to the dialog. Can you check how many modals are lacking, if there aren't many, we should add those in this pr itself @gramo37

**Comment by gramo37** [comment]
Hi @Amit91848, I have fixed the first issue you mentioned (clicking outside the modal removes query parameters from the URL but doesn’t do so for drawers, preventing the modal from reopening). I also resolved the 'Out of Office' issue and updated the same in the other modals as well.

**Comment by keithwillcode** [comment]
Closing for now due to staleness.

**Pull request closed without merging**
